export enum LANG {
  uz = 'uz',
  oz = 'oz',
}

export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}

export enum TypeSearch {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
}

export enum OperationType {
  EQUAL = '=',
  NOT_EQUAL = '!=',
  GREATER_THAN = '>',
  LESS_THAN = '<',
  GREATER_THAN_OR_EQUAL = '>=',
  LESS_THAN_OR_EQUAL = '<=',
  IN = 'in',
  LIKE = 'LIKE',
  WILDCARD = '%_%',
}

export enum LANG_TYPE {
  ADMIN_CABINET = 'ADMIN_CABINET',
  CLIENT_CABINET = 'CLIENT_CABINET',
}

export enum Permissions {
  // Users
  VIEW_USERS = 'VIEW_USERS',
  VIEW_USER = 'VIEW_USER',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Roles
  VIEW_ROLES = 'VIEW_ROLES',
  VIEW_ROLE = 'VIEW_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Blogs
  VIEW_BLOGS = 'VIEW_BLOGS',
  VIEW_BLOG = 'VIEW_BLOG',
  CREATE_BLOG = 'CREATE_BLOG',
  UPDATE_BLOG = 'UPDATE_BLOG',
  DELETE_BLOG = 'DELETE_BLOG',

  // Names of God
  VIEW_NAMES_OF_GOD = 'VIEW_NAMES_OF_GOD',
  VIEW_NAME_OF_GOD = 'VIEW_NAME_OF_GOD',
  CREATE_NAME_OF_GOD = 'CREATE_NAME_OF_GOD',
  UPDATE_NAME_OF_GOD = 'UPDATE_NAME_OF_GOD',
  DELETE_NAME_OF_GOD = 'DELETE_NAME_OF_GOD',

  // Special Questions
  VIEW_SPECIAL_QUESTIONS = 'VIEW_SPECIAL_QUESTIONS',
  VIEW_SPECIAL_QUESTION = 'VIEW_SPECIAL_QUESTION',
  CREATE_SPECIAL_QUESTION = 'CREATE_SPECIAL_QUESTION',
  UPDATE_SPECIAL_QUESTION = 'UPDATE_SPECIAL_QUESTION',
  DELETE_SPECIAL_QUESTION = 'DELETE_SPECIAL_QUESTION',

  // Daily Wisdoms
  VIEW_DAILY_WISDOMS = 'VIEW_DAILY_WISDOMS',
  VIEW_DAILY_WISDOM = 'VIEW_DAILY_WISDOM',
  CREATE_DAILY_WISDOM = 'CREATE_DAILY_WISDOM',
  UPDATE_DAILY_WISDOM = 'UPDATE_DAILY_WISDOM',
  DELETE_DAILY_WISDOM = 'DELETE_DAILY_WISDOM',

  // Islamic Sayings
  VIEW_ISLAMIC_SAYINGS = 'VIEW_ISLAMIC_SAYINGS',
  VIEW_ISLAMIC_SAYING = 'VIEW_ISLAMIC_SAYING',
  CREATE_ISLAMIC_SAYING = 'CREATE_ISLAMIC_SAYING',
  UPDATE_ISLAMIC_SAYING = 'UPDATE_ISLAMIC_SAYING',
  DELETE_ISLAMIC_SAYING = 'DELETE_ISLAMIC_SAYING',

  // Pillars of Islam
  VIEW_PILLARS_OF_ISLAM = 'VIEW_PILLARS_OF_ISLAM',
  VIEW_PILLAR_OF_ISLAM = 'VIEW_PILLAR_OF_ISLAM',
  CREATE_PILLAR_OF_ISLAM = 'CREATE_PILLAR_OF_ISLAM',
  UPDATE_PILLAR_OF_ISLAM = 'UPDATE_PILLAR_OF_ISLAM',
  DELETE_PILLAR_OF_ISLAM = 'DELETE_PILLAR_OF_ISLAM',

  // Duas
  VIEW_DUAS = 'VIEW_DUAS',
  VIEW_DUA = 'VIEW_DUA',
  CREATE_DUA = 'CREATE_DUA',
  UPDATE_DUA = 'UPDATE_DUA',
  DELETE_DUA = 'DELETE_DUA',

  // Videos
  VIEW_VIDEOS = 'VIEW_VIDEOS',
  VIEW_VIDEO = 'VIEW_VIDEO',
  CREATE_VIDEO = 'CREATE_VIDEO',
  UPDATE_VIDEO = 'UPDATE_VIDEO',
  DELETE_VIDEO = 'DELETE_VIDEO',

  // Audios
  VIEW_AUDIOS = 'VIEW_AUDIOS',
  VIEW_AUDIO = 'VIEW_AUDIO',
  CREATE_AUDIO = 'CREATE_AUDIO',
  UPDATE_AUDIO = 'UPDATE_AUDIO',
  DELETE_AUDIO = 'DELETE_AUDIO',

  // Photos
  VIEW_PHOTOS = 'VIEW_PHOTOS',
  VIEW_PHOTO = 'VIEW_PHOTO',
  CREATE_PHOTO = 'CREATE_PHOTO',
  UPDATE_PHOTO = 'UPDATE_PHOTO',
  DELETE_PHOTO = 'DELETE_PHOTO',

  // Media Categories
  VIEW_MEDIA_CATEGORIES = 'VIEW_MEDIA_CATEGORIES',
  VIEW_MEDIA_CATEGORY = 'VIEW_MEDIA_CATEGORY',
  CREATE_MEDIA_CATEGORY = 'CREATE_MEDIA_CATEGORY',
  UPDATE_MEDIA_CATEGORY = 'UPDATE_MEDIA_CATEGORY',
  DELETE_MEDIA_CATEGORY = 'DELETE_MEDIA_CATEGORY',

  // Partners
  VIEW_PARTNERS = 'VIEW_PARTNERS',
  VIEW_PARTNER = 'VIEW_PARTNER',
  CREATE_PARTNER = 'CREATE_PARTNER',
  UPDATE_PARTNER = 'UPDATE_PARTNER',
  DELETE_PARTNER = 'DELETE_PARTNER',

  // Banners
  VIEW_BANNERS = 'VIEW_BANNERS',
  VIEW_BANNER = 'VIEW_BANNER',
  CREATE_BANNER = 'CREATE_BANNER',
  UPDATE_BANNER = 'UPDATE_BANNER',
  DELETE_BANNER = 'DELETE_BANNER',

  // Social Networks
  VIEW_NETWORKS = 'VIEW_NETWORKS',
  VIEW_NETWORK = 'VIEW_NETWORK',
  CREATE_NETWORK = 'CREATE_NETWORK',
  UPDATE_NETWORK = 'UPDATE_NETWORK',
  DELETE_NETWORK = 'DELETE_NETWORK',

  // Page Infos
  VIEW_PAGE_INFOS = 'VIEW_PAGE_INFOS',
  CREATE_PAGE_INFO = 'CREATE_PAGE_INFO',

  // Translations
  VIEW_TRANSLATIONS = 'VIEW_TRANSLATIONS',
  VIEW_TRANSLATION = 'VIEW_TRANSLATION',
  CREATE_TRANSLATION = 'CREATE_TRANSLATION',
  UPDATE_TRANSLATION = 'UPDATE_TRANSLATION',
  DELETE_TRANSLATION = 'DELETE_TRANSLATION',
}
